apiVersion: extensions/v1beta1 # for versions before 1.9.0 use apps/v1beta2
kind: Deployment
metadata:
  name: gomaji-usagi
  labels:
    app: g-usagi
    version: latest
spec:
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  selector:
    matchLabels:
      app: g-usagi
  template:
    metadata:
      labels:
        app: g-usagi
        version: latest
    spec:
      containers:
      - name: g-usagi
        image: docker03.gomaji.com/release/usagi:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 80
        env:
          - name: environment
            value: uat
