apiVersion: extensions/v1beta1 # for versions before 1.9.0 use apps/v1beta2
kind: Deployment
metadata:
  name: gomaji-usagi
  labels:
    app: g-usagi
    version: {{build.commit}}
spec:
  replicas: 2
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  selector:
    matchLabels:
      app: g-usagi
  template:
    metadata:
      labels:
        app: g-usagi
        version: {{build.commit}}
    spec:
      containers:
      - name: g-usagi
        image: docker03.gomaji.com/release/usagi:{{build.commit}}
        imagePullPolicy: Always
        ports:
        - containerPort: 80
        env:
          - name: environment
            value: uat
        livenessProbe:
            initialDelaySeconds: 10
            periodSeconds: 300
            timeoutSeconds: 3
            successThreshold: 1
            failureThreshold: 1
            httpGet:
              path: /api/healthy
              port: 80
