<?php

return [
    /*
     * 基本城市列表（英文名稱 => id）
     */
    'baseCityList' => [
        'taipei' => 1,
        'taoyuan' => 2,
        'hsinchu' => 3,
        'taichung' => 4,
        'tainan' => 5,
        'kaohsiung' => 6,
        'taiwan' => 7,
        'miaoli' => 8,
        'changhua' => 9,
        'nantou' => 10,
        'yunlin' => 11,
        'chiayi' => 12,
        'pingtung' => 13,
        'taitung' => 14,
        'hualien' => 15,
        'yilan' => 16,
        'keelung' => 17,
        'travel' => 18,
        'publicWelfare' => 19,
        'newTaipei' => 20,
        'ticket' => 21,
    ],

    /*
     * 基本城市列表（id => 英文名稱）
     */
    'baseCityEngList' => [
        1 => 'Taipei',
        2 => 'Taoyuan',
        3 => 'Hsinchu',
        4 => 'Taichung',
        5 => 'Tainan',
        6 => 'Kaohsiung',
        7 => 'Taiwan',
        8 => 'Miaoli',
        9 => 'Changhua',
        10 => 'Nantou',
        11 => 'Yunlin',
        12 => 'Chiayi',
        13 => 'Pingtung',
        14 => 'Taitung',
        15 => 'Hualien',
        16 => 'Yilan',
        17 => 'Keelung',
        18 => 'Travel',
        19 => 'PublicWelfare',
        20 => 'NewTaipei',
        21 => 'Ticket',
    ],

    /*
     * 城市列表
     */
    'cityList' => [
        0 => ['name' => '全國地區', 'paramValue' => 'city=0&dist_group=0', 'subCity' => []],
        1 => ['name' => '大台北', 'paramValue' => 'city=1&dist_group=0', 'subCity' => [
            1 => ['name' => '松山區', 'paramValue' => 'city=1&dist_group=1'],
            2 => ['name' => '信義區', 'paramValue' => 'city=1&dist_group=2'],
            3 => ['name' => '大安區', 'paramValue' => 'city=1&dist_group=3'],
            4 => ['name' => '中山區', 'paramValue' => 'city=1&dist_group=4'],
            5 => ['name' => '中正區', 'paramValue' => 'city=1&dist_group=5'],
            6 => ['name' => '大同區', 'paramValue' => 'city=1&dist_group=6'],
            7 => ['name' => '內湖區', 'paramValue' => 'city=1&dist_group=7'],
            8 => ['name' => '士林區', 'paramValue' => 'city=1&dist_group=8'],
            9 => ['name' => '北投區', 'paramValue' => 'city=1&dist_group=9'],
            10 => ['name' => '萬華區', 'paramValue' => 'city=1&dist_group=10'],
            11 => ['name' => '文山區', 'paramValue' => 'city=1&dist_group=11'],
            12 => ['name' => '南港區', 'paramValue' => 'city=1&dist_group=12'],
            68 => ['name' => '板橋區', 'paramValue' => 'city=1&dist_group=68'],
            69 => ['name' => '新莊區', 'paramValue' => 'city=1&dist_group=69'],
            70 => ['name' => '三重區', 'paramValue' => 'city=1&dist_group=70'],
            71 => ['name' => '中和區', 'paramValue' => 'city=1&dist_group=71'],
            72 => ['name' => '永和區', 'paramValue' => 'city=1&dist_group=72'],
            73 => ['name' => '新店區', 'paramValue' => 'city=1&dist_group=73'],
            74 => ['name' => '土城區', 'paramValue' => 'city=1&dist_group=74'],
            75 => ['name' => '蘆洲區', 'paramValue' => 'city=1&dist_group=75'],
            16 => ['name' => '新北其它', 'paramValue' => 'city=1&dist_group=16'],],],
        2 => ['name' => '桃園', 'paramValue' => 'city=2&dist_group=0', 'subCity' => []],
        3 => ['name' => '新竹', 'paramValue' => 'city=3&dist_group=0', 'subCity' => []],
        8 => ['name' => '苗栗', 'paramValue' => 'city=8&dist_group=0', 'subCity' => []],
        4 => ['name' => '台中', 'paramValue' => 'city=4&dist_group=0', 'subCity' => [
            77 => ['name' => '中區', 'paramValue' => 'city=4&dist_group=77'],
            78 => ['name' => '東區', 'paramValue' => 'city=4&dist_group=78'],
            79 => ['name' => '南區', 'paramValue' => 'city=4&dist_group=79'],
            80 => ['name' => '西區', 'paramValue' => 'city=4&dist_group=80'],
            81 => ['name' => '北區', 'paramValue' => 'city=4&dist_group=81'],
            82 => ['name' => '北屯區', 'paramValue' => 'city=4&dist_group=82'],
            83 => ['name' => '西屯區', 'paramValue' => 'city=4&dist_group=83'],
            84 => ['name' => '南屯區', 'paramValue' => 'city=4&dist_group=84'],
            85 => ['name' => '太平區', 'paramValue' => 'city=4&dist_group=85'],
            86 => ['name' => '大里區', 'paramValue' => 'city=4&dist_group=86'],
            87 => ['name' => '大雅區', 'paramValue' => 'city=4&dist_group=87'],
            88 => ['name' => '沙鹿區', 'paramValue' => 'city=4&dist_group=88'],
            89 => ['name' => '豐原區', 'paramValue' => 'city=4&dist_group=89'],
            90 => ['name' => '台中其它', 'paramValue' => 'city=4&dist_group=90]'],],],
        9 => ['name' => '彰化', 'paramValue' => 'city=9&dist_group=0', 'subCity' => []],
        10 => ['name' => '南投', 'paramValue' => 'city=10&dist_group=0', 'subCity' => []],
        11 => ['name' => '雲林', 'paramValue' => 'city=11&dist_group=0', 'subCity' => []],
        12 => ['name' => '嘉義', 'paramValue' => 'city=12&dist_group=0', 'subCity' => []],
        5 => ['name' => '台南', 'paramValue' => 'city=5&dist_group=0', 'subCity' => []],
        6 => ['name' => '高雄', 'paramValue' => 'city=6&dist_group=0', 'subCity' => [
            91 => ['name' => '楠梓區', 'paramValue' => 'city=6&dist_group=91'],
            92 => ['name' => '左營區', 'paramValue' => 'city=6&dist_group=92'],
            93 => ['name' => '鼓山區', 'paramValue' => 'city=6&dist_group=93'],
            94 => ['name' => '三民區', 'paramValue' => 'city=6&dist_group=94'],
            95 => ['name' => '鹽埕區', 'paramValue' => 'city=6&dist_group=95'],
            96 => ['name' => '前金區', 'paramValue' => 'city=6&dist_group=96'],
            97 => ['name' => '新興區', 'paramValue' => 'city=6&dist_group=97'],
            98 => ['name' => '苓雅區', 'paramValue' => 'city=6&dist_group=98'],
            99 => ['name' => '前鎮區', 'paramValue' => 'city=6&dist_group=99'],
            100 => ['name' => '鳳山區', 'paramValue' => 'city=6&dist_group=100'],
            101 => ['name' => '高雄其它', 'paramValue' => 'city=6&dist_group=101'],],],
        13 => ['name' => '屏東', 'paramValue' => 'city=13&dist_group=0', 'subCity' => []],
        14 => ['name' => '台東', 'paramValue' => 'city=14&dist_group=0', 'subCity' => []],
        15 => ['name' => '花蓮', 'paramValue' => 'city=15&dist_group=0', 'subCity' => []],
        16 => ['name' => '宜蘭', 'paramValue' => 'city=16&dist_group=0', 'subCity' => []],
        17 => ['name' => '基隆', 'paramValue' => 'city=17&dist_group=0', 'subCity' => []],
    ],

    /*
     * 地區列表
     */
    'regionList' => [
        0 => ['name' => '全國地區', 'paramValue' => 'region=0&city=0&spot=0', 'subCity' => []],
        1 => ['name' => '北部地區', 'paramValue' => 'region=1&city=0&spot=0', 'subCity' => [
            1 => ['name' => '大台北', 'paramValue' => 'region=1&city=1&spot=0', 'subCity' => [
                45 => ['name' => '北投．陽明山', 'paramValue' => 'region=1&city=1&spot=45'],
                67 => ['name' => '西門町', 'paramValue' => 'region=1&city=1&spot=67'],
                46 => ['name' => '三峽．鶯歌', 'paramValue' => 'region=1&city=1&spot=46'],
                47 => ['name' => '淡水．八里', 'paramValue' => 'region=1&city=1&spot=47'],
                48 => ['name' => '三芝．石門．金山．萬里', 'paramValue' => 'region=1&city=1&spot=48'],
                49 => ['name' => '烏來．深坑', 'paramValue' => 'region=1&city=1&spot=49'],
                50 => ['name' => '瑞芳．九份．福隆', 'paramValue' => 'region=1&city=1&spot=50'],],],
            17 => ['name' => '基隆', 'paramValue' => 'region=1&city=17&spot=0', 'subCity' => []],
            2 => ['name' => '桃園', 'paramValue' => 'region=1&city=2&spot=0', 'subCity' => []],
            3 => ['name' => '新竹', 'paramValue' => 'region=1&city=3&spot=0', 'subCity' => []],
            8 => ['name' => '苗栗', 'paramValue' => 'region=1&city=8&spot=0', 'subCity' => [
                51 => ['name' => '三義．大湖．泰安．南庄', 'paramValue' => 'region=1&city=8&spot=51'],],],],],
        2 => ['name' => '中部地區', 'paramValue' => 'region=2&city=0&spot=0', 'subCity' => [
            4 => ['name' => '台中', 'paramValue' => 'region=2&city=4&spot=0', 'subCity' => [
                52 => ['name' => '新社．谷關', 'paramValue' => 'region=2&city=4&spot=52'],
                53 => ['name' => '逢甲．一中', 'paramValue' => 'region=2&city=4&spot=53'],],],
            9 => ['name' => '彰化', 'paramValue' => 'region=2&city=9&spot=0', 'subCity' => []],
            10 => ['name' => '南投', 'paramValue' => 'region=2&city=10&spot=0', 'subCity' => [
                54 => ['name' => '廬山．清境', 'paramValue' => 'region=2&city=10&spot=54'],
                55 => ['name' => '埔里．日月潭', 'paramValue' => 'region=2&city=10&spot=55'],
                56 => ['name' => '溪頭．杉林溪', 'paramValue' => 'region=2&city=10&spot=56'],
                57 => ['name' => '集集．草屯', 'paramValue' => 'region=2&city=10&spot=57'],],],],],
        3 => ['name' => '南部地區', 'paramValue' => 'region=3&city=0&spot=0', 'subCity' => [
            11 => ['name' => '雲林', 'paramValue' => 'region=3&city=11&spot=0', 'subCity' => []],
            12 => ['name' => '嘉義', 'paramValue' => 'region=3&city=12&spot=0', 'subCity' => [
                65 => ['name' => '阿里山', 'paramValue' => 'region=3&city=12&spot=65'],],],
            5 => ['name' => '台南', 'paramValue' => 'region=3&city=5&spot=0', 'subCity' => []],
            6 => ['name' => '高雄', 'paramValue' => 'region=3&city=6&spot=0', 'subCity' => []],
            13 => ['name' => '屏東', 'paramValue' => 'region=3&city=13&spot=0', 'subCity' => [
                58 => ['name' => '墾丁．恆春', 'paramValue' => 'region=3&city=13&spot=58'],
                59 => ['name' => '小琉球．東港', 'paramValue' => 'region=3&city=13&spot=59'],
                60 => ['name' => '三地門', 'paramValue' => 'region=3&city=13&spot=60'],],],],],
        4 => ['name' => '宜花東地區', 'paramValue' => 'region=4&city=0&spot=0', 'subCity' => [
            16 => ['name' => '宜蘭', 'paramValue' => 'region=4&city=16&spot=0', 'subCity' => [
                61 => ['name' => '礁溪．頭城．宜蘭市', 'paramValue' => 'region=4&city=16&spot=61'],
                62 => ['name' => '羅東．蘇澳．太平山', 'paramValue' => 'region=4&city=16&spot=62'],],],
            15 => ['name' => '花蓮', 'paramValue' => 'region=4&city=15&spot=0', 'subCity' => []],
            14 => ['name' => '台東', 'paramValue' => 'region=4&city=14&spot=0', 'subCity' => [
                63 => ['name' => '鹿野．池上．知本', 'paramValue' => 'region=4&city=14&spot=63'],
                66 => ['name' => '綠島．蘭嶼', 'paramValue' => 'region=4&city=14&spot=66'],],],
            18 => ['name' => '離島', 'paramValue' => 'region=4&city=18&spot=0', 'subCity' => [
                64 => ['name' => '澎湖．金門．馬祖', 'paramValue' => 'region=4&city=18&spot=64'],],],],],
    ],

    /*
     * 鄉鎮市及郵遞區號
     */
    'districtAndZipcode' => [
        ['id' => 1, 'name' => '台北', 'sub_categories' => [
            ['name' => '中正區', 'zip_code' => 100],
            ['name' => '大同區', 'zip_code' => 103],
            ['name' => '中山區', 'zip_code' => 104],
            ['name' => '松山區', 'zip_code' => 105],
            ['name' => '大安區', 'zip_code' => 106],
            ['name' => '萬華區', 'zip_code' => 108],
            ['name' => '信義區', 'zip_code' => 110],
            ['name' => '士林區', 'zip_code' => 111],
            ['name' => '北投區', 'zip_code' => 112],
            ['name' => '內湖區', 'zip_code' => 114],
            ['name' => '南港區', 'zip_code' => 115],
            ['name' => '文山區', 'zip_code' => 116],
        ]],
        ['id' => 2, 'name' => '桃園', 'sub_categories' => [
            ['name' => '中壢區', 'zip_code' => 320],
            ['name' => '平鎮區', 'zip_code' => 324],
            ['name' => '龍潭區', 'zip_code' => 325],
            ['name' => '楊梅區', 'zip_code' => 326],
            ['name' => '新屋區', 'zip_code' => 327],
            ['name' => '觀音區', 'zip_code' => 328],
            ['name' => '桃園區', 'zip_code' => 330],
            ['name' => '龜山區', 'zip_code' => 333],
            ['name' => '八德區', 'zip_code' => 334],
            ['name' => '大溪區', 'zip_code' => 335],
            ['name' => '復興區', 'zip_code' => 336],
            ['name' => '大園區', 'zip_code' => 337],
            ['name' => '蘆竹區', 'zip_code' => 338],
        ]],
        ['id' => 3, 'name' => '新竹', 'sub_categories' => [
            ['name' => '東區', 'zip_code' => 300],
            ['name' => '北區', 'zip_code' => 300],
            ['name' => '香山區', 'zip_code' => 300],
            ['name' => '竹北市', 'zip_code' => 302],
            ['name' => '湖口鄉', 'zip_code' => 303],
            ['name' => '新豐鄉', 'zip_code' => 304],
            ['name' => '新埔鎮', 'zip_code' => 305],
            ['name' => '關西鎮', 'zip_code' => 306],
            ['name' => '芎林鄉', 'zip_code' => 307],
            ['name' => '寶山鄉', 'zip_code' => 308],
            ['name' => '竹東鎮', 'zip_code' => 310],
            ['name' => '五峰鄉', 'zip_code' => 311],
            ['name' => '橫山鄉', 'zip_code' => 312],
            ['name' => '尖石鄉', 'zip_code' => 313],
            ['name' => '北埔鄉', 'zip_code' => 314],
            ['name' => '峨眉鄉', 'zip_code' => 315],
        ]],
        ['id' => 4, 'name' => '台中', 'sub_categories' => [
            ['name' => '中區', 'zip_code' => 400],
            ['name' => '東區', 'zip_code' => 401],
            ['name' => '南區', 'zip_code' => 402],
            ['name' => '西區', 'zip_code' => 403],
            ['name' => '北區', 'zip_code' => 404],
            ['name' => '北屯區', 'zip_code' => 406],
            ['name' => '西屯區', 'zip_code' => 407],
            ['name' => '南屯區', 'zip_code' => 408],
            ['name' => '太平區', 'zip_code' => 411],
            ['name' => '大里區', 'zip_code' => 412],
            ['name' => '霧峰區', 'zip_code' => 413],
            ['name' => '烏日區', 'zip_code' => 414],
            ['name' => '豐原區', 'zip_code' => 420],
            ['name' => '后里區', 'zip_code' => 421],
            ['name' => '石岡區', 'zip_code' => 422],
            ['name' => '東勢區', 'zip_code' => 423],
            ['name' => '和平區', 'zip_code' => 424],
            ['name' => '新社區', 'zip_code' => 426],
            ['name' => '潭子區', 'zip_code' => 427],
            ['name' => '大雅區', 'zip_code' => 428],
            ['name' => '神岡區', 'zip_code' => 429],
            ['name' => '大肚區', 'zip_code' => 432],
            ['name' => '沙鹿區', 'zip_code' => 433],
            ['name' => '龍井區', 'zip_code' => 434],
            ['name' => '梧棲區', 'zip_code' => 435],
            ['name' => '清水區', 'zip_code' => 436],
            ['name' => '大甲區', 'zip_code' => 437],
            ['name' => '外埔區', 'zip_code' => 438],
            ['name' => '大安區', 'zip_code' => 439],
        ]],
        ['id' => 5, 'name' => '台南', 'sub_categories' => [
            ['name' => '中西區', 'zip_code' => 700],
            ['name' => '東區', 'zip_code' => 701],
            ['name' => '南區', 'zip_code' => 702],
            ['name' => '北區', 'zip_code' => 704],
            ['name' => '安平區', 'zip_code' => 708],
            ['name' => '安南區', 'zip_code' => 709],
            ['name' => '永康區', 'zip_code' => 710],
            ['name' => '歸仁區', 'zip_code' => 711],
            ['name' => '新化區', 'zip_code' => 712],
            ['name' => '左鎮區', 'zip_code' => 713],
            ['name' => '玉井區', 'zip_code' => 714],
            ['name' => '楠西區', 'zip_code' => 715],
            ['name' => '南化區', 'zip_code' => 716],
            ['name' => '仁德區', 'zip_code' => 717],
            ['name' => '關廟區', 'zip_code' => 718],
            ['name' => '龍崎區', 'zip_code' => 719],
            ['name' => '官田區', 'zip_code' => 720],
            ['name' => '麻豆區', 'zip_code' => 721],
            ['name' => '佳里區', 'zip_code' => 722],
            ['name' => '西港區', 'zip_code' => 723],
            ['name' => '七股區', 'zip_code' => 724],
            ['name' => '將軍區', 'zip_code' => 725],
            ['name' => '學甲區', 'zip_code' => 726],
            ['name' => '北門區', 'zip_code' => 727],
            ['name' => '新營區', 'zip_code' => 730],
            ['name' => '後壁區', 'zip_code' => 731],
            ['name' => '白河區', 'zip_code' => 732],
            ['name' => '東山區', 'zip_code' => 733],
            ['name' => '六甲區', 'zip_code' => 734],
            ['name' => '下營區', 'zip_code' => 735],
            ['name' => '柳營區', 'zip_code' => 736],
            ['name' => '鹽水區', 'zip_code' => 737],
            ['name' => '善化區', 'zip_code' => 741],
            ['name' => '大內區', 'zip_code' => 742],
            ['name' => '山上區', 'zip_code' => 743],
            ['name' => '新市區', 'zip_code' => 744],
            ['name' => '安定區', 'zip_code' => 745],
        ]],
        ['id' => 6, 'name' => '高雄', 'sub_categories' => [
            ['name' => '新興區', 'zip_code' => 800],
            ['name' => '前金區', 'zip_code' => 801],
            ['name' => '苓雅區', 'zip_code' => 802],
            ['name' => '鹽埕區', 'zip_code' => 803],
            ['name' => '鼓山區', 'zip_code' => 804],
            ['name' => '旗津區', 'zip_code' => 805],
            ['name' => '前鎮區', 'zip_code' => 806],
            ['name' => '三民區', 'zip_code' => 807],
            ['name' => '楠梓區', 'zip_code' => 811],
            ['name' => '小港區', 'zip_code' => 812],
            ['name' => '左營區', 'zip_code' => 813],
            ['name' => '仁武區', 'zip_code' => 814],
            ['name' => '大社區', 'zip_code' => 815],
            ['name' => '岡山區', 'zip_code' => 820],
            ['name' => '路竹區', 'zip_code' => 821],
            ['name' => '阿蓮區', 'zip_code' => 822],
            ['name' => '田寮區', 'zip_code' => 823],
            ['name' => '燕巢區', 'zip_code' => 824],
            ['name' => '橋頭區', 'zip_code' => 825],
            ['name' => '梓官區', 'zip_code' => 826],
            ['name' => '彌陀區', 'zip_code' => 827],
            ['name' => '永安區', 'zip_code' => 828],
            ['name' => '湖內區', 'zip_code' => 829],
            ['name' => '鳳山區', 'zip_code' => 830],
            ['name' => '大寮區', 'zip_code' => 831],
            ['name' => '林園區', 'zip_code' => 832],
            ['name' => '鳥松區', 'zip_code' => 833],
            ['name' => '大樹區', 'zip_code' => 840],
            ['name' => '旗山區', 'zip_code' => 842],
            ['name' => '美濃區', 'zip_code' => 843],
            ['name' => '六龜區', 'zip_code' => 844],
            ['name' => '內門區', 'zip_code' => 845],
            ['name' => '杉林區', 'zip_code' => 846],
            ['name' => '甲仙區', 'zip_code' => 847],
            ['name' => '桃源區', 'zip_code' => 848],
            ['name' => '那瑪夏', 'zip_code' => 849],
            ['name' => '茂林區', 'zip_code' => 851],
            ['name' => '茄萣區', 'zip_code' => 852],

        ]],
        ['id' => 8, 'name' => '苗栗', 'sub_categories' => [
            ['name' => '竹南鎮', 'zip_code' => 350],
            ['name' => '頭份市', 'zip_code' => 351],
            ['name' => '三灣鄉', 'zip_code' => 352],
            ['name' => '南庄鄉', 'zip_code' => 353],
            ['name' => '獅潭鄉', 'zip_code' => 354],
            ['name' => '後龍鎮', 'zip_code' => 356],
            ['name' => '通霄鎮', 'zip_code' => 357],
            ['name' => '苑裡鎮', 'zip_code' => 358],
            ['name' => '苗栗市', 'zip_code' => 360],
            ['name' => '造橋鄉', 'zip_code' => 361],
            ['name' => '頭屋鄉', 'zip_code' => 362],
            ['name' => '公館鄉', 'zip_code' => 363],
            ['name' => '大湖鄉', 'zip_code' => 364],
            ['name' => '泰安鄉', 'zip_code' => 365],
            ['name' => '銅鑼鄉', 'zip_code' => 366],
            ['name' => '三義鄉', 'zip_code' => 367],
            ['name' => '西湖鄉', 'zip_code' => 368],
            ['name' => '卓蘭鎮', 'zip_code' => 369],
        ]],
        ['id' => 9, 'name' => '彰化', 'sub_categories' => [
            ['name' => '彰化市', 'zip_code' => 500],
            ['name' => '芬園鄉', 'zip_code' => 502],
            ['name' => '花壇鄉', 'zip_code' => 503],
            ['name' => '秀水鄉', 'zip_code' => 504],
            ['name' => '鹿港鎮', 'zip_code' => 505],
            ['name' => '福興鄉', 'zip_code' => 506],
            ['name' => '線西鄉', 'zip_code' => 507],
            ['name' => '和美鎮', 'zip_code' => 508],
            ['name' => '伸港鄉', 'zip_code' => 509],
            ['name' => '員林市', 'zip_code' => 510],
            ['name' => '社頭鄉', 'zip_code' => 511],
            ['name' => '永靖鄉', 'zip_code' => 512],
            ['name' => '埔心鄉', 'zip_code' => 513],
            ['name' => '溪湖鎮', 'zip_code' => 514],
            ['name' => '大村鄉', 'zip_code' => 515],
            ['name' => '埔鹽鄉', 'zip_code' => 516],
            ['name' => '田中鎮', 'zip_code' => 520],
            ['name' => '北斗鎮', 'zip_code' => 521],
            ['name' => '田尾鄉', 'zip_code' => 522],
            ['name' => '埤頭鄉', 'zip_code' => 523],
            ['name' => '溪州鄉', 'zip_code' => 524],
            ['name' => '竹塘鄉', 'zip_code' => 525],
            ['name' => '二林鎮', 'zip_code' => 526],
            ['name' => '大城鄉', 'zip_code' => 527],
            ['name' => '芳苑鄉', 'zip_code' => 528],
            ['name' => '二水鄉', 'zip_code' => 530],
        ]],
        ['id' => 10, 'name' => '南投', 'sub_categories' => [
            ['name' => '南投市', 'zip_code' => 540],
            ['name' => '中寮鄉', 'zip_code' => 541],
            ['name' => '草屯鎮', 'zip_code' => 542],
            ['name' => '國姓鄉', 'zip_code' => 544],
            ['name' => '埔里鎮', 'zip_code' => 545],
            ['name' => '仁愛鄉', 'zip_code' => 546],
            ['name' => '名間鄉', 'zip_code' => 551],
            ['name' => '集集鎮', 'zip_code' => 552],
            ['name' => '水里鄉', 'zip_code' => 553],
            ['name' => '魚池鄉', 'zip_code' => 555],
            ['name' => '信義鄉', 'zip_code' => 556],
            ['name' => '竹山鎮', 'zip_code' => 557],
            ['name' => '鹿谷鄉', 'zip_code' => 558],
        ]],
        ['id' => 11, 'name' => '雲林', 'sub_categories' => [
            ['name' => '斗南鎮', 'zip_code' => 630],
            ['name' => '大埤鄉', 'zip_code' => 631],
            ['name' => '虎尾鎮', 'zip_code' => 632],
            ['name' => '土庫鎮', 'zip_code' => 633],
            ['name' => '褒忠鄉', 'zip_code' => 634],
            ['name' => '東勢鄉', 'zip_code' => 635],
            ['name' => '台西鄉', 'zip_code' => 636],
            ['name' => '崙背鄉', 'zip_code' => 637],
            ['name' => '麥寮鄉', 'zip_code' => 638],
            ['name' => '斗六市', 'zip_code' => 640],
            ['name' => '林內鄉', 'zip_code' => 643],
            ['name' => '古坑鄉', 'zip_code' => 646],
            ['name' => '莿桐鄉', 'zip_code' => 647],
            ['name' => '西螺鎮', 'zip_code' => 648],
            ['name' => '二崙鄉', 'zip_code' => 649],
            ['name' => '北港鎮', 'zip_code' => 651],
            ['name' => '水林鄉', 'zip_code' => 652],
            ['name' => '口湖鄉', 'zip_code' => 653],
            ['name' => '四湖鄉', 'zip_code' => 654],
            ['name' => '元長鄉', 'zip_code' => 655],
        ]],
        ['id' => 12, 'name' => '嘉義', 'sub_categories' => [
            ['name' => '東區', 'zip_code' => 600],
            ['name' => '西區', 'zip_code' => 600],
            ['name' => '番路鄉', 'zip_code' => 602],
            ['name' => '梅山鄉', 'zip_code' => 603],
            ['name' => '竹崎鄉', 'zip_code' => 604],
            ['name' => '阿里山', 'zip_code' => 605],
            ['name' => '中埔鄉', 'zip_code' => 606],
            ['name' => '大埔鄉', 'zip_code' => 607],
            ['name' => '水上鄉', 'zip_code' => 608],
            ['name' => '鹿草鄉', 'zip_code' => 611],
            ['name' => '太保市', 'zip_code' => 612],
            ['name' => '朴子市', 'zip_code' => 613],
            ['name' => '東石鄉', 'zip_code' => 614],
            ['name' => '六腳鄉', 'zip_code' => 615],
            ['name' => '新港鄉', 'zip_code' => 616],
            ['name' => '民雄鄉', 'zip_code' => 621],
            ['name' => '大林鎮', 'zip_code' => 622],
            ['name' => '溪口鄉', 'zip_code' => 623],
            ['name' => '義竹鄉', 'zip_code' => 624],
            ['name' => '布袋鎮', 'zip_code' => 625],
        ]],
        ['id' => 13, 'name' => '屏東', 'sub_categories' => [
            ['name' => '屏東市', 'zip_code' => 900],
            ['name' => '三地門', 'zip_code' => 901],
            ['name' => '霧台鄉', 'zip_code' => 902],
            ['name' => '瑪家鄉', 'zip_code' => 903],
            ['name' => '九如鄉', 'zip_code' => 904],
            ['name' => '里港鄉', 'zip_code' => 905],
            ['name' => '高樹鄉', 'zip_code' => 906],
            ['name' => '鹽埔鄉', 'zip_code' => 907],
            ['name' => '長治鄉', 'zip_code' => 908],
            ['name' => '麟洛鄉', 'zip_code' => 909],
            ['name' => '竹田鄉', 'zip_code' => 911],
            ['name' => '內埔鄉', 'zip_code' => 912],
            ['name' => '萬丹鄉', 'zip_code' => 913],
            ['name' => '潮州鎮', 'zip_code' => 920],
            ['name' => '泰武鄉', 'zip_code' => 921],
            ['name' => '來義鄉', 'zip_code' => 922],
            ['name' => '萬巒鄉', 'zip_code' => 923],
            ['name' => '崁頂鄉', 'zip_code' => 924],
            ['name' => '新埤鄉', 'zip_code' => 925],
            ['name' => '南州鄉', 'zip_code' => 926],
            ['name' => '林邊鄉', 'zip_code' => 927],
            ['name' => '東港鎮', 'zip_code' => 928],
            ['name' => '佳冬鄉', 'zip_code' => 931],
            ['name' => '新園鄉', 'zip_code' => 932],
            ['name' => '枋寮鄉', 'zip_code' => 940],
            ['name' => '枋山鄉', 'zip_code' => 941],
            ['name' => '春日鄉', 'zip_code' => 942],
            ['name' => '獅子鄉', 'zip_code' => 943],
            ['name' => '車城鄉', 'zip_code' => 944],
            ['name' => '牡丹鄉', 'zip_code' => 945],
            ['name' => '恆春鎮', 'zip_code' => 946],
            ['name' => '滿州鄉', 'zip_code' => 947],
        ]],
        ['id' => 14, 'name' => '台東', 'sub_categories' => [
            ['name' => '台東市', 'zip_code' => 950],
            ['name' => '延平鄉', 'zip_code' => 953],
            ['name' => '卑南鄉', 'zip_code' => 954],
            ['name' => '鹿野鄉', 'zip_code' => 955],
            ['name' => '關山鎮', 'zip_code' => 956],
            ['name' => '海端鄉', 'zip_code' => 957],
            ['name' => '池上鄉', 'zip_code' => 958],
            ['name' => '東河鄉', 'zip_code' => 959],
            ['name' => '成功鎮', 'zip_code' => 961],
            ['name' => '長濱鄉', 'zip_code' => 962],
            ['name' => '太麻里', 'zip_code' => 963],
            ['name' => '金峰鄉', 'zip_code' => 964],
            ['name' => '大武鄉', 'zip_code' => 965],
            ['name' => '達仁鄉', 'zip_code' => 966],
        ]],
        ['id' => 15, 'name' => '花蓮', 'sub_categories' => [
            ['name' => '花蓮市', 'zip_code' => 970],
            ['name' => '新城鄉', 'zip_code' => 971],
            ['name' => '秀林鄉', 'zip_code' => 972],
            ['name' => '吉安鄉', 'zip_code' => 973],
            ['name' => '壽豐鄉', 'zip_code' => 974],
            ['name' => '鳳林鎮', 'zip_code' => 975],
            ['name' => '光復鄉', 'zip_code' => 976],
            ['name' => '豐濱鄉', 'zip_code' => 977],
            ['name' => '瑞穗鄉', 'zip_code' => 978],
            ['name' => '萬榮鄉', 'zip_code' => 979],
            ['name' => '玉里鎮', 'zip_code' => 981],
            ['name' => '卓溪鄉', 'zip_code' => 982],
            ['name' => '富里鄉', 'zip_code' => 983],
        ]],
        ['id' => 16, 'name' => '宜蘭', 'sub_categories' => [
            ['name' => '宜蘭市', 'zip_code' => 260],
            ['name' => '頭城鎮', 'zip_code' => 261],
            ['name' => '礁溪鄉', 'zip_code' => 262],
            ['name' => '壯圍鄉', 'zip_code' => 263],
            ['name' => '員山鄉', 'zip_code' => 264],
            ['name' => '羅東鎮', 'zip_code' => 265],
            ['name' => '三星鄉', 'zip_code' => 266],
            ['name' => '大同鄉', 'zip_code' => 267],
            ['name' => '五結鄉', 'zip_code' => 268],
            ['name' => '冬山鄉', 'zip_code' => 269],
            ['name' => '蘇澳鎮', 'zip_code' => 270],
            ['name' => '南澳鄉', 'zip_code' => 272],
        ]],
        ['id' => 17, 'name' => '基隆', 'sub_categories' => [
            ['name' => '仁愛區', 'zip_code' => 200],
            ['name' => '信義區', 'zip_code' => 201],
            ['name' => '中正區', 'zip_code' => 202],
            ['name' => '中山區', 'zip_code' => 203],
            ['name' => '安樂區', 'zip_code' => 204],
            ['name' => '暖暖區', 'zip_code' => 205],
            ['name' => '七堵區', 'zip_code' => 206],
        ]],
        ['id' => 20, 'name' => '新北', 'sub_categories' => [
            ['name' => '萬里區', 'zip_code' => 207],
            ['name' => '金山區', 'zip_code' => 208],
            ['name' => '板橋區', 'zip_code' => 220],
            ['name' => '汐止區', 'zip_code' => 221],
            ['name' => '深坑區', 'zip_code' => 222],
            ['name' => '石碇區', 'zip_code' => 223],
            ['name' => '瑞芳區', 'zip_code' => 224],
            ['name' => '平溪區', 'zip_code' => 226],
            ['name' => '雙溪區', 'zip_code' => 227],
            ['name' => '貢寮區', 'zip_code' => 228],
            ['name' => '新店區', 'zip_code' => 231],
            ['name' => '坪林區', 'zip_code' => 232],
            ['name' => '烏來區', 'zip_code' => 233],
            ['name' => '永和區', 'zip_code' => 234],
            ['name' => '中和區', 'zip_code' => 235],
            ['name' => '土城區', 'zip_code' => 236],
            ['name' => '三峽區', 'zip_code' => 237],
            ['name' => '樹林區', 'zip_code' => 238],
            ['name' => '鶯歌區', 'zip_code' => 239],
            ['name' => '三重區', 'zip_code' => 241],
            ['name' => '新莊區', 'zip_code' => 242],
            ['name' => '泰山區', 'zip_code' => 243],
            ['name' => '林口區', 'zip_code' => 244],
            ['name' => '蘆洲區', 'zip_code' => 247],
            ['name' => '五股區', 'zip_code' => 248],
            ['name' => '八里區', 'zip_code' => 249],
            ['name' => '淡水區', 'zip_code' => 251],
            ['name' => '三芝區', 'zip_code' => 252],
            ['name' => '石門區', 'zip_code' => 253],
        ]],
    ],

    /*
     * EDM 訂閱城市列表
     */
    'edmCityList' => [
        1 => [
            'name' => '台北',
            'newline' => false,
        ],
        2 => [
            'name' => '桃園',
            'newline' => false,
        ],
        3 => [
            'name' => '新竹',
            'newline' => false,
        ],
        4 => [
            'name' => '台中',
            'newline' => false,
        ],
        5 => [
            'name' => '台南',
            'newline' => false,
        ],
        6 => [
            'name' => '高雄',
            'newline' => false,
        ],
        18 => [
            'name' => '旅遊&旅遊行程',
            'newline' => true,
        ],
        7 => [
            'name' => '宅配美食',
            'newline' => true,
        ],
    ],

    /*
     * 創市際 取得各區域
     */
    'areaList' => [
        0 => [
            'id' => '1',
            'name' => '台北市',
        ],
        1 => [
            'id' => '2',
            'name' => '基隆市',
        ],
        2 => [
            'id' => '3',
            'name' => '新北市',
        ],
        3 => [
            'id' => '4',
            'name' => '宜蘭縣',
        ],
        4 => [
            'id' => '5',
            'name' => '桃園縣',
        ],
        5 => [
            'id' => '6',
            'name' => '新竹市',
        ],
        6 => [
            'id' => '7',
            'name' => '新竹縣',
        ],
        7 => [
            'id' => '8',
            'name' => '苗栗縣',
        ],
        8 => [
            'id' => '9',
            'name' => '台中市',
        ],
        9 => [
            'id' => '11',
            'name' => '彰化縣',
        ],
        10 => [
            'id' => '12',
            'name' => '南投縣',
        ],
        11 => [
            'id' => '13',
            'name' => '嘉義市',
        ],
        12 => [
            'id' => '14',
            'name' => '嘉義縣',
        ],
        13 => [
            'id' => '15',
            'name' => '雲林縣',
        ],
        14 => [
            'id' => '16',
            'name' => '台南市',
        ],
        15 => [
            'id' => '18',
            'name' => '高雄市',
        ],
        16 => [
            'id' => '20',
            'name' => '屏東縣',
        ],
        17 => [
            'id' => '21',
            'name' => '花蓮縣',
        ],
        18 => [
            'id' => '22',
            'name' => '台東縣',
        ],
        19 => [
            'id' => '23',
            'name' => '澎湖縣',
        ],
        20 => [
            'id' => '24',
            'name' => '金門縣',
        ],
        21 => [
            'id' => '25',
            'name' => '連江縣',
        ],
        22 => [
            'id' => '30',
            'name' => '其他地區',
        ],
    ],

    /*
     * 會員資料蒐集頁 城市選單
     */
    'accountCityList' => [
        ['id' => 1, 'name' => '台北'],
        ['id' => 20, 'name' => '新北'],
        ['id' => 17, 'name' => '基隆'],
        ['id' => 2, 'name' => '桃園'],
        ['id' => 3, 'name' => '新竹'],
        ['id' => 8, 'name' => '苗栗'],
        ['id' => 4, 'name' => '台中'],
        ['id' => 9, 'name' => '彰化'],
        ['id' => 10, 'name' => '南投'],
        ['id' => 11, 'name' => '雲林'],
        ['id' => 12, 'name' => '嘉義'],
        ['id' => 5, 'name' => '台南'],
        ['id' => 6, 'name' => '高雄'],
        ['id' => 13, 'name' => '屏東'],
        ['id' => 14, 'name' => '台東'],
        ['id' => 15, 'name' => '花蓮'],
        ['id' => 16, 'name' => '宜蘭'],
        ['id' => 22, 'name' => '外島地區'],
        ['id' => 23, 'name' => '海外'],
    ],
];
